export const clients = [
    {
        id: 1,
        name: "Raj Sharma",
        caseType: "Property Dispute",
        status: "Pending",
        documents: 4,
        uploaded: ["Sale deed", "Ownership proof", "Identification"],
        pending: ["Title report", "Verification certificate"],
        timeline: ["Client Registered", "Documents Uploaded", "Verification Complete", "Draft Preparation", "Court Filing"],
    },
    {
        id: 2,
        name: "Aman Verma",
        caseType: "Corporate Compliance",
        status: "Approved",
        documents: 6,
        uploaded: ["Board resolution", "Financial statements", "KYC"],
        pending: ["Registrar approval"],
        timeline: ["Client Registered", "Documents Uploaded", "Verification Complete", "Draft Preparation", "Court Filing"],
    },
    {
        id: 3,
        name: "Sneha Kapoor",
        caseType: "Family Settlement",
        status: "Review",
        documents: 3,
        uploaded: ["Affidavit", "Mediation report"],
        pending: ["Court notice"],
        timeline: ["Client Registered", "Documents Uploaded", "Verification Complete", "Draft Preparation", "Court Filing"],
    },
    {
        id: 4,
        name: "Vikram Joshi",
        caseType: "Employment Contract",
        status: "Approved",
        documents: 5,
        uploaded: ["Draft contract", "ID proofs", "Notification letters"],
        pending: ["Final contract sign-off"],
        timeline: ["Client Registered", "Documents Uploaded", "Verification Complete", "Draft Preparation", "Court Filing"],
    },
    {
        id: 5,
        name: "Pooja Singh",
        caseType: "Tax Audit",
        status: "Pending",
        documents: 7,
        uploaded: ["Income records", "Tax returns", "PAN details"],
        pending: ["Audit report", "Clarification notes"],
        timeline: ["Client Registered", "Documents Uploaded", "Audit Started", "Review Pending", "Finalization"],
    },
    {
        id: 6,
        name: "Deepak Malhotra",
        caseType: "Intellectual Property",
        status: "Review",
        documents: 4,
        uploaded: ["Patent draft", "Design specs", "ID proof"],
        pending: ["Prior art search", "Application fee"],
        timeline: ["Client Registered", "Documents Uploaded", "Research Started", "Review Pending", "Filing Preparation"],
    },
    {
        id: 7,
        name: "Anjali Reddy",
        caseType: "Lease Agreement",
        status: "Approved",
        documents: 6,
        uploaded: ["Draft lease", "Property papers", "KYC"],
        pending: ["Landlord signature"],
        timeline: ["Client Registered", "Documents Uploaded", "Verification Complete", "Draft Preparation", "Signing Scheduled"],
    },
    {
        id: 8,
        name: "Rohit Mehra",
        caseType: "Criminal Defense",
        status: "Pending",
        documents: 5,
        uploaded: ["Police FIR", "Bail papers", "Character affidavits"],
        pending: ["Court hearing", "Witness statements"],
        timeline: ["Client Registered", "Documents Uploaded", "Review Started", "Strategy Draft", "Court Preparation"],
    },
    {
        id: 9,
        name: "Nina Patel",
        caseType: "Startup Incorporation",
        status: "Approved",
        documents: 8,
        uploaded: ["MOA", "AOA", "Founder IDs", "Capital statement"],
        pending: ["Registrar approval"],
        timeline: ["Client Registered", "Documents Uploaded", "Verification Complete", "Application Filed", "Approval Received"],
    },
    {
        id: 10,
        name: "Saurabh Desai",
        caseType: "Consumer Complaint",
        status: "Review",
        documents: 3,
        uploaded: ["Complaint copy", "Receipt", "Warranty"],
        pending: ["Response from seller"],
        timeline: ["Client Registered", "Documents Uploaded", "Review Started", "Notice Draft", "Submission"],
    },
];

export const stats = [
    { title: "Total Clients", value: "24 Clients" },
    { title: "Active Cases", value: "12 Active Cases" },
    { title: "Pending Documents", value: "18 Pending Docs" },
    { title: "Closed Cases", value: "6 Closed Cases" },
];

export const activity = [
    "Raj Sharma uploaded property papers",
    "Aman Verma case moved to review",
    "Hearing scheduled",
];

export const progress = {
    label: "Case Completion",
    value: 80,
};
